name: Token outside

# on:
#   workflow_dispatch
#
on: 
  push:

jobs:
     
  ingest:
    runs-on: ubuntu-latest
    permissions: write-all
    # strategy: 
    #   matrix:
    #     notebook: 
          
    steps:
      - name: Generate AAD Token
        run: |
          echo "DATABRICKS_TOKEN=$(curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
          https://login.microsoftonline.com/${{ secrets.AZURE_SP_TENANT_ID }}/oauth2/v2.0/token \
          -d 'client_id=${{ secrets.AZURE_SP_APPLICATION_ID }}' \
          -d 'grant_type=client_credentials' \
          -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
          -d 'client_secret=${{ secrets.AZURE_SP_CLIENT_SECRET }}' |  jq -r  '.access_token')" >> $GITHUB_ENV
      
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Save secret
        run: gh secret set TESTING_SECRET --body "$DATABRICKS_TOKEN" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - name: test-run
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /formula1/ingestion/1.ingest_circuits_file
          # workspace-notebook-path: /formula1/ingestion/${{ matrix.notebook }}
          # local-notebook-path: ../../formula1/ingestion/1.ingest_circuits_file
          databricks-host: https://adb-8718332331325895.15.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          git-commit: ${{ github.event.pull_request.head.sha }}
          existing-cluster-id: 0703-104318-wm62xcqc