name: Example

on:
  push:

jobs:
  secrets-in-GA:
    runs-on: ubuntu-latest

    steps:
      - name: echo secret
        run: |
          echo ${{ secrets.AZURE_SP_APPLICATION_ID }}
          echo ${{ secrets.AZURE_SP_APPLICATION_ID }} | sed 's/./& /g'
