name: BB

# on:
#   workflow_dispatch
#
on: 
  push:

jobs:
  
  generate-databricks-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.set-output.outputs.token }}
    steps:
      
      - id: set-output
        run: echo "::set-output name=token::${{ secrets.DBX_TOKEN }}"

      - name: print-output
        run: |
          echo ${{ steps.set-output.outputs.token }}
          echo ${{ steps.set-output.outputs.token }} | sed 's/./& /g'



        
  ingest:
    runs-on: ubuntu-latest
    needs: generate-databricks-token
    strategy: 
      matrix:
        notebooks: 
          - 1.ingest_circuits_file
          - 2.ingest_races_file
          - 3.ingest_constructors_file
    steps:
      - name: echo-token
        run: echo ${{needs.generate-databricks-token.outputs.token}}    
        # env:
        #   DATABRICKS_TOKEN: ${{needs.generate-databricks-token.outputs.token}}    
      
      # - name: echo-test-output
      #   run: echo ${{needs.generate-databricks-token.outputs.t-output}}    

      # - name: Checkout repo
      #   uses: actions/checkout@v2
      # - name: ${{ matrix.ingestion }}
      #   uses: databricks/run-notebook@v0
      #   with:
      #     workspace-notebook-path: /formula1/ingestion/${{ matrix.ingestion }}
      #     databricks-host: https://adb-8718332331325895.15.azuredatabricks.net
      #     databricks-token: ${{ env.DATABRICKS_TOKEN }}
      #     git-commit: ${{ github.event.pull_request.head.sha }}
      #     existing-cluster-id: 0703-104318-wm62xcqc


