name: Token outside

# on:
#   workflow_dispatch
#
on: 
  push:

jobs:
     
  ingest:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        notebook: 
          - 1.ingest_circuits_file
          - 2.ingest_races_file
          - 3.ingest_constructors_file
    steps:
      - name: echo-token
        run: echo ${{ secrets.DBX_TOKEN }}    
     
      - name: echo-path
        run: echo /formula1/ingestion/${{ matrix.notebook }}

      - name: Checkout repo
        uses: actions/checkout@v2
      - name: ${{ matrix.ingestion }}
        uses: databricks/run-notebook@v0
        with:
          workspace-notebook-path: /formula1/ingestion/1.ingest_circuits_file
          # workspace-notebook-path: /formula1/ingestion/${{ matrix.notebook }}
          databricks-host: https://adb-8718332331325895.15.azuredatabricks.net
          databricks-token: ${{ secrets.DBX_TOKEN }}
          git-commit: ${{ github.event.pull_request.head.sha }}
          existing-cluster-id: 0703-104318-wm62xcqc